backend:
  name: github
  repo: "lupapelie/lupapelie.github.io"  # Nome do seu repositório no GitHub
  branch: main  # Ou 'principal', dependendo do seu branch principal

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    folder: "/"
    create: false
    slug: "index.html"  # Esse é o arquivo que o CMS irá editar diretamente
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
