backend:
  name: GitHub
  repo: "lupapelie/lupapelie.github.io"  # Este é o seu repositório no GitHub
  branch: principal  # ou 'main', dependendo do seu branch principal

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
