backend:
  name: github
  repo: "lupapelie/lupapelie.github.io"  # O repositório correto no GitHub
  branch: main  # Ou 'principal', se for o seu branch principal

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "postagens"
    label: "Postagens"
    folder: "content/postagens"  # Caminho para a pasta de postagens
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "title"  # Adicionando o campo identificador como "title"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Corpo", name: "corpo", widget: "markdown" }
