backend:
  name: github
  repo: "lupapelie/lupapelie.github.io"  # Seu repositório no GitHub
  branch: main  # ou 'principal', dependendo do seu branch principal

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "postagens"
    label: "Postagens"
    folder: "content/postagens"  # Caminho para a pasta de postagens
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "title"  # Aqui está o campo de identificador correto, como "title"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Corpo", name: "corpo", widget: "markdown" }
